# Site settings
title: RIA-utveckling med JavaScript
email: yoyoyowazzup[kanelbulle]hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Elin Nilssons kursblogg för kursen RIA-utveckling med JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: elinnilsson90
github_username:  swoot1

# Build settings
markdown: kramdown
